Repository jejuHackathon/jeju-hackathon, pull requests merged in 2022-08, with the labels that each got.

#8 [BE] DB 모델링 적용 및 세팅
  mysite/main/models.py
  mysite/main/views.py
  mysite/tutorialdjango/settings.py
Labels: BE, Feature

#10 [BE] DB Table 수정
  mysite/db.sqlite3
  mysite/geom.png
  mysite/geomsub.png
  mysite/main/__pycache__/__init__.cpython-310.pyc
  mysite/main/__pycache__/admin.cpython-310.pyc
  mysite/main/__pycache__/apps.cpython-310.pyc
  mysite/main/__pycache__/models.cpython-310.pyc
  mysite/main/admin.py
  mysite/main/migrations/0001_initial.py
  mysite/main/migrations/__pycache__/0001_initial.cpython-310.pyc
  mysite/main/migrations/__pycache__/__init__.cpython-310.pyc
  mysite/main/models.py
  mysite/media/geom.png
  mysite/media/geom_PgRDk0Y.png
  mysite/media/geomsub.png
  mysite/media/geomsub_EAGoFLN.png
  mysite/tutorialdjango/__pycache__/__init__.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/settings.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/urls.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/wsgi.cpython-310.pyc
  mysite/tutorialdjango/settings.py
Labels: BE, Feature

#12 BE branch dev Brach merge
  mysite/db.sqlite3
  mysite/geom.png
  mysite/geomsub.png
  mysite/main/__pycache__/__init__.cpython-310.pyc
  mysite/main/__pycache__/admin.cpython-310.pyc
  mysite/main/__pycache__/apps.cpython-310.pyc
  mysite/main/__pycache__/models.cpython-310.pyc
  mysite/main/admin.py
  mysite/main/migrations/0001_initial.py
  mysite/main/migrations/__pycache__/0001_initial.cpython-310.pyc
  mysite/main/migrations/__pycache__/__init__.cpython-310.pyc
  mysite/main/models.py
  mysite/main/views.py
  mysite/media/geom.png
  mysite/media/geom_PgRDk0Y.png
  mysite/media/geomsub.png
  mysite/media/geomsub_EAGoFLN.png
  mysite/tutorialdjango/__pycache__/__init__.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/settings.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/urls.cpython-310.pyc
  mysite/tutorialdjango/__pycache__/wsgi.cpython-310.pyc
  mysite/tutorialdjango/settings.py
Labels: BE

#14 [FE] Create HTML & CSS 작업완료
  mysite/main/static/css/common.css
  mysite/main/static/css/create.css
  mysite/main/static/css/index.css
  mysite/main/static/css/variable.css
  mysite/main/static/js/create.js
  mysite/main/templates/main/base.html
  mysite/main/templates/main/create.html
Labels: FE, Feature

#16 [FE] Detail Page 마크업 진행, CSS 공통된 부분 common쪽으로 분리
  mysite/main/static/css/common.css
  mysite/main/static/css/create.css
  mysite/main/static/css/oreum.css
  mysite/main/templates/main/detail.html
  mysite/main/templates/main/list.html
Labels: FE, Feature

#18 [BE] urls.py 및 view.py 임시 설정
  mysite/main/static/css/common.css
  mysite/main/static/css/create.css
  mysite/main/static/css/index.css
  mysite/main/static/css/oreum.css
  mysite/main/static/css/variable.css
  mysite/main/static/icons/instagram.svg
  mysite/main/static/icons/location.svg
  mysite/main/static/icons/phone.svg
  mysite/main/static/images/sample.png
  mysite/main/static/js/create.js
  mysite/main/templates/main/base.html
  mysite/main/templates/main/create.html
  mysite/main/templates/main/detail.html
  mysite/main/templates/main/list.html
  mysite/main/views.py
  mysite/tutorialdjango/urls.py
Labels: BE, Feature

#19 [FE] main 페이지 마크업 & CSS
  mysite/main/static/css/home.css
  mysite/main/static/css/index.css
  mysite/main/templates/main/base.html
  mysite/main/templates/main/index.html
Labels: FE, Feature
